### PR TITLE
Fix flaky `SlidingWindowTest`

### LINKED ISSUE #956: Flaky test - SlidingWindowTest
After merging a PR, I saw a test failure.

https://app.circleci.com/pipelines/github/prometheus/client_java/1242/workflows/4701f003-e272-466f-aa78-6f437fe2dc1f/jobs/1330

Rerunning the workflow, the test was successful.

```
java.lang.AssertionError: Start time: 1715203446644, current time: 1715203476654, elapsed time: 30010 expected:<[2.0]> but was:<[1.0, 2.0]>
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.failNotEquals(Assert.java:835)
        at org.junit.Assert.assertEquals(Assert.java:120)
        at io.prometheus.metrics.core.metrics.SlidingWindowTest$Observer.assertValues(SlidingWindowTest.java:26)
        at io.prometheus.metrics.core.metrics.SlidingWindowTest.testMultiRotate(SlidingWindowTest.java:71)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
        at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
```

### PR DESCRIPTION
**Pull request by Stephan202**
Observed in the context of PicnicSupermarket/error-prone-support#1468, this PR aims to resolve the following transient test failure:
```
[ERROR] io.prometheus.metrics.core.metrics.SlidingWindowTest.rotate -- Time elapsed: 0.023 s <<< FAILURE!
org.opentest4j.AssertionFailedError:
[Start time: 1734782202868, current time: 1734782232878, elapsed time: 30010]
expected: [1.0, 1.0, 1.0, 1.0, 1.0]
 but was: [1.0, 1.0, 1.0, 1.0]
    at io.prometheus.metrics.core.metrics.SlidingWindowTest$Observer.assertValues(SlidingWindowTest.java:30)
    at io.prometheus.metrics.core.metrics.SlidingWindowTest.rotate(SlidingWindowTest.java:57)
    at java.base/java.lang.reflect.Method.invoke(Method.java:569)
    at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
    at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
```

This fix likely also resolves #956.

How to reproduce:
```
mvn install -DskipTests -pl prometheus-metrics-core -am
while mvn test -Dtest='SlidingWindowTest' -pl prometheus-metrics-core; do echo Again...; done
```

Prior to this fix the loop exists after a few minutes (or even significantly faster), while with this change the loop does not appear to terminate.

### CODE REVIEW

File: prometheus-metrics-core/src/test/java/io/prometheus/metrics/core/metrics/SlidingWindowTest.java [hunk 1]
```diff
@@ -40,7 +40,7 @@ void assertValues(double... expectedValues) {
   private SlidingWindow<Observer> ringBuffer;
   private final long maxAgeSeconds = 30;
   private final int ageBuckets = 5;
-  private final long timeBetweenRotateMillis = maxAgeSeconds * 1000 / ageBuckets + 2;
+  private final long timeBetweenRotateMillis = maxAgeSeconds * 1000 / ageBuckets;
```
Comment (Stephan202) [inline prometheus-metrics-core/src/test/java/io/prometheus/metrics/core/metrics/SlidingWindowTest.java:43]: This fix assumes that dropping the `+ 2` doesn't reduce coverage in a meaningful way. At first glance that appears to be so :eyes:

**Comment by Stephan202** [comment]
Alight, so somehow I filed to rerun the full test class; I could swear I did that before opening the PR. :facepalm: I'm having a closer look at this issue and will try to propose a fix that doesn't cause the other test to fail. Sorry for the noise! Will close PR until I have a proposal.

**Comment by Stephan202** [comment]
Alright, I pushed a proper fix: it turns out that `SlidingWindow#lastRotateTimestampMillis` was assigned before the test reassigned the `LongSupplier currentTimeMillis`. I resolved this by introducing a constructor overload instead.

File: prometheus-metrics-core/src/test/java/io/prometheus/metrics/core/metrics/SlidingWindowTest.java (hunk 1 above)
Comment (Stephan202) [reply prometheus-metrics-core/src/test/java/io/prometheus/metrics/core/metrics/SlidingWindowTest.java]: I reverted this change; the updated fix only takes away the source of non-determinism.

**Comment by Stephan202** [comment]
Squashed the commits and rewrite the PR title and summary.

**Review by rickie — APPROVED** [review]
