### PR TITLE
Invoke processCpuTime with reflection to bridge ibm/sun diffs

### LINKED ISSUE #174: Be compatible with IBM JDK in a lenient way
DefaultExports.initialize() will add register (among other) StandardExports.
StandardExports has two com.sun.management classes.
It will fail on a IBM JDK with:
```
[1/10/17 10:19:50:691 CET] 00000021 com.ibm.ws.webcontainer.webapp                               E SRVE0283E: Exception caught while initializing context: java.lang.ClassCastException: com.ibm.lang.management.UnixExtendedOperatingSystem incompatible with com.sun.management.OperatingSystemMXBean
        at io.prometheus.client.hotspot.StandardExports.<init>(StandardExports.java:43)
        at io.prometheus.client.hotspot.DefaultExports.initialize(DefaultExports.java:23)
```

I think it would be better to 
1) use java.lang.managment where possible, and where it does not provide the additional metrics we want:
2) use some classload-test to see if the classes are available, and if not, skip registering.

### PR DESCRIPTION
**Pull request by davidkarlsen**
Fixes #174

---
This change is [Reviewable](https://reviewable.io/reviews/prometheus/client_java/176)

### CODE REVIEW

File: simpleclient_hotspot/src/main/java/io/prometheus/client/hotspot/StandardExports.java [hunk 1]
```diff
@@ -56,8 +58,19 @@ public StandardExports() {
   public List<MetricFamilySamples> collect() {
     List<MetricFamilySamples> mfs = new ArrayList<MetricFamilySamples>();
 
-    mfs.add(new CounterMetricFamily("process_cpu_seconds_total", "Total user and system CPU time spent in seconds.",
-        osBean.getProcessCpuTime() / NANOSECONDS_PER_SECOND));
+    try {
+      Method method = osBean.getClass().getMethod("getProcessCpuTime", null);
+      if (!method.isAccessible()) {
```
Comment (brian-brazil) [inline simpleclient_hotspot/src/main/java/io/prometheus/client/hotspot/StandardExports.java]: Why do you have to do this?

File: simpleclient_hotspot/src/main/java/io/prometheus/client/hotspot/StandardExports.java [hunk 2]
```diff
@@ -56,8 +58,19 @@ public StandardExports() {
...
+        method.setAccessible(true);
+      }
+      Long l = (Long) method.invoke(osBean);
+          mfs.add(new CounterMetricFamily("process_cpu_seconds_total", "Total user and system CPU time spent in seconds.",
+                  l / NANOSECONDS_PER_SECOND));
+    }
+    catch ( Exception e ) {
+      LOGGER.log(Level.WARNING, "Could not access process cpu time", e);
```
Comment (brian-brazil) [inline simpleclient_hotspot/src/main/java/io/prometheus/client/hotspot/StandardExports.java]: This would get very spammy, debug is enough

File: simpleclient_hotspot/src/main/java/io/prometheus/client/hotspot/StandardExports.java [hunk 3]
```diff
@@ -56,8 +58,19 @@ public StandardExports() {
...
+    try {
+      Method method = osBean.getClass().getMethod("getProcessCpuTime", null);
+      if (!method.isAccessible()) {
+        method.setAccessible(true);
+      }
+      Long l = (Long) method.invoke(osBean);
+          mfs.add(new CounterMetricFamily("process_cpu_seconds_total", "Total user and system CPU time spent in seconds.",
+                  l / NANOSECONDS_PER_SECOND));
+    }
+    catch ( Exception e ) {
```
Comment (brian-brazil) [inline simpleclient_hotspot/src/main/java/io/prometheus/client/hotspot/StandardExports.java]: No spaces inside the () to keep consistent

File: simpleclient_hotspot/src/main/java/io/prometheus/client/hotspot/StandardExports.java [hunk 4]
```diff
@@ -56,8 +58,19 @@ public StandardExports() {
   public List<MetricFamilySamples> collect() {
     List<MetricFamilySamples> mfs = new ArrayList<MetricFamilySamples>();
 
-    mfs.add(new CounterMetricFamily("process_cpu_seconds_total", "Total user and system CPU time spent in seconds.",
-        osBean.getProcessCpuTime() / NANOSECONDS_PER_SECOND));
+    try {
+      Method method = osBean.getClass().getMethod("getProcessCpuTime", null);
```
Comment (brian-brazil) [inline simpleclient_hotspot/src/main/java/io/prometheus/client/hotspot/StandardExports.java]: This all needs a comment

File: simpleclient_hotspot/src/main/java/io/prometheus/client/hotspot/StandardExports.java (hunk 1 above)
Comment (davidkarlsen) [inline simpleclient_hotspot/src/main/java/io/prometheus/client/hotspot/StandardExports.java]: calling by reflection because there will be different implementing classes on IBM/Oracle JDK.
setAccessible because it's public *native*

File: simpleclient_hotspot/src/main/java/io/prometheus/client/hotspot/StandardExports.java (hunk 3 above)
Comment (davidkarlsen) [inline simpleclient_hotspot/src/main/java/io/prometheus/client/hotspot/StandardExports.java]: fxied

File: simpleclient_hotspot/src/main/java/io/prometheus/client/hotspot/StandardExports.java (hunk 2 above)
Comment (davidkarlsen) [inline simpleclient_hotspot/src/main/java/io/prometheus/client/hotspot/StandardExports.java]: fixed

File: simpleclient_hotspot/src/main/java/io/prometheus/client/hotspot/StandardExports.java (hunk 4 above)
Comment (davidkarlsen) [inline simpleclient_hotspot/src/main/java/io/prometheus/client/hotspot/StandardExports.java]: fixed

File: simpleclient_hotspot/src/main/java/io/prometheus/client/hotspot/StandardExports.java (hunk 1 above)
Comment (brian-brazil) [inline simpleclient_hotspot/src/main/java/io/prometheus/client/hotspot/StandardExports.java]: Why would it being native change accessibility?

Comment (davidkarlsen) [inline simpleclient_hotspot/src/main/java/io/prometheus/client/hotspot/StandardExports.java]: Sorry - brainfreeze.
The class has default access, that's why the method needs to be set accessible: https://github.com/frohoff/jdk8u-jdk/blob/master/src/solaris/classes/sun/management/OperatingSystemImpl.java - naturally I don't have Oracle sources available as a reference on Internet - but same there if you step debug into it.

Comment (brian-brazil) [inline simpleclient_hotspot/src/main/java/io/prometheus/client/hotspot/StandardExports.java]: Those are all public access, not default.

Comment (davidkarlsen) [inline simpleclient_hotspot/src/main/java/io/prometheus/client/hotspot/StandardExports.java]: The method, yes, not the class. So the if test will fail, it will go inside, and set it accessible. Without it it will fail...

Comment (brian-brazil) [inline simpleclient_hotspot/src/main/java/io/prometheus/client/hotspot/StandardExports.java]: How is the current code working at all then?

Comment (davidkarlsen) [inline simpleclient_hotspot/src/main/java/io/prometheus/client/hotspot/StandardExports.java]: ? It sets it accessible, invokes the method, and returns the result as before?

Comment (brian-brazil) [inline simpleclient_hotspot/src/main/java/io/prometheus/client/hotspot/StandardExports.java]: I meant that if the current code also has a default access class, why isn't it failing?

Comment (davidkarlsen) [inline simpleclient_hotspot/src/main/java/io/prometheus/client/hotspot/StandardExports.java]: Ah - now I follow you, because Oracle provides it through https://docs.oracle.com/javase/7/docs/jre/api/management/extension/com/sun/management/OperatingSystemMXBean.html which was the interface used before, but now it's a concrete class, which either implements that iface, or com.ibm.lang.management.OperatingSystemMXBean (also an iface) - depending on the VM-flavour - but the common superinterface they both (IBM/Oracle) implement does not expose  getProcessCpuTime().

Comment (brian-brazil) [inline simpleclient_hotspot/src/main/java/io/prometheus/client/hotspot/StandardExports.java]: Okay then. This still needs a comment explaining all this.

Comment (davidkarlsen) [inline simpleclient_hotspot/src/main/java/io/prometheus/client/hotspot/StandardExports.java]: okidok - added further comments.

File: simpleclient_hotspot/src/main/java/io/prometheus/client/hotspot/StandardExports.java [hunk 5]
```diff
@@ -56,8 +58,24 @@ public StandardExports() {
   public List<MetricFamilySamples> collect() {
     List<MetricFamilySamples> mfs = new ArrayList<MetricFamilySamples>();
 
-    mfs.add(new CounterMetricFamily("process_cpu_seconds_total", "Total user and system CPU time spent in seconds.",
-        osBean.getProcessCpuTime() / NANOSECONDS_PER_SECOND));
+    try {
+      /*
+      there are two interfaces com.ibm.lang.management.OperatingSystemMXBean and com.sun.management.OperatingSystemMXBean,
```
Comment (brian-brazil) [inline simpleclient_hotspot/src/main/java/io/prometheus/client/hotspot/StandardExports.java]: There

File: simpleclient_hotspot/src/main/java/io/prometheus/client/hotspot/StandardExports.java [hunk 6]
```diff
@@ -56,8 +58,24 @@ public StandardExports() {
...
+      but no common interface which exposes getProcessCpuTime, hence call on the implementing class, which is default access,
```
Comment (brian-brazil) [inline simpleclient_hotspot/src/main/java/io/prometheus/client/hotspot/StandardExports.java]: getProcessCpuTime. Hence

File: simpleclient_hotspot/src/main/java/io/prometheus/client/hotspot/StandardExports.java [hunk 7]
```diff
@@ -56,8 +58,24 @@ public StandardExports() {
...
+      */
+      Method method = osBean.getClass().getMethod("getProcessCpuTime", null);
+      if (!method.isAccessible()) {
+        method.setAccessible(true);
+      }
+      Long l = (Long) method.invoke(osBean);
+          mfs.add(new CounterMetricFamily("process_cpu_seconds_total","Total user and system CPU time spent in seconds.",
+                  l / NANOSECONDS_PER_SECOND));
+    }
+    catch ( Exception e ) {
```
Comment (brian-brazil) [inline simpleclient_hotspot/src/main/java/io/prometheus/client/hotspot/StandardExports.java]: spaces in ()

File: simpleclient_hotspot/src/main/java/io/prometheus/client/hotspot/StandardExports.java [hunk 8]
```diff
@@ -56,8 +58,24 @@ public StandardExports() {
   public List<MetricFamilySamples> collect() {
     List<MetricFamilySamples> mfs = new ArrayList<MetricFamilySamples>();
 
-    mfs.add(new CounterMetricFamily("process_cpu_seconds_total", "Total user and system CPU time spent in seconds.",
-        osBean.getProcessCpuTime() / NANOSECONDS_PER_SECOND));
+    try {
+      /*
+      there are two interfaces com.ibm.lang.management.OperatingSystemMXBean and com.sun.management.OperatingSystemMXBean,
+      but no common interface which exposes getProcessCpuTime, hence call on the implementing class, which is default access,
+      so use reflection hack to set it accessible and avoid riding around the different ifaces and whatnot
```
Comment (brian-brazil) [inline simpleclient_hotspot/src/main/java/io/prometheus/client/hotspot/StandardExports.java]: accessible. - and end it there

File: simpleclient_hotspot/src/main/java/io/prometheus/client/hotspot/StandardExports.java (hunk 5 above)
Comment (davidkarlsen) [inline simpleclient_hotspot/src/main/java/io/prometheus/client/hotspot/StandardExports.java]: fixed

File: simpleclient_hotspot/src/main/java/io/prometheus/client/hotspot/StandardExports.java (hunk 6 above)
Comment (davidkarlsen) [inline simpleclient_hotspot/src/main/java/io/prometheus/client/hotspot/StandardExports.java]: fixed

File: simpleclient_hotspot/src/main/java/io/prometheus/client/hotspot/StandardExports.java (hunk 8 above)
Comment (davidkarlsen) [inline simpleclient_hotspot/src/main/java/io/prometheus/client/hotspot/StandardExports.java]: fixed

File: simpleclient_hotspot/src/main/java/io/prometheus/client/hotspot/StandardExports.java (hunk 7 above)
Comment (davidkarlsen) [inline simpleclient_hotspot/src/main/java/io/prometheus/client/hotspot/StandardExports.java]: fixed - given this is ok then, could we have a relase?

File: simpleclient_hotspot/src/main/java/io/prometheus/client/hotspot/StandardExports.java [hunk 9]
```diff
@@ -56,8 +58,24 @@ public StandardExports() {
...
+      There are two interfaces com.ibm.lang.management.OperatingSystemMXBean and com.sun.management.OperatingSystemMXBean,
+      but no common interface which exposes getProcessCpuTime. Hence call on the implementing class, which is default access,
+      so use reflection hack to set it accessible.
+      */
+      Method method = osBean.getClass().getMethod("getProcessCpuTime", null);
+      if (!method.isAccessible()) {
+        method.setAccessible(true);
+      }
+      Long l = (Long) method.invoke(osBean);
+          mfs.add(new CounterMetricFamily("process_cpu_seconds_total","Total user and system CPU time spent in seconds.",
```
Comment (brian-brazil) [inline simpleclient_hotspot/src/main/java/io/prometheus/client/hotspot/StandardExports.java]: space after comma here, and below in the log line.

Comment (davidkarlsen) [inline simpleclient_hotspot/src/main/java/io/prometheus/client/hotspot/StandardExports.java]: Hmm, they do not appear in my editor?

Comment (brian-brazil) [inline simpleclient_hotspot/src/main/java/io/prometheus/client/hotspot/StandardExports.java]: You're definitely still missing spaces. Are you sure you've pushed the latest version to github?

Comment (davidkarlsen) [inline simpleclient_hotspot/src/main/java/io/prometheus/client/hotspot/StandardExports.java]: Maybe github does not show whitespace updates correctly? Looks ok here: https://reviewable.io/reviews/prometheus/client_java/176 ?

**Comment by brian-brazil** [comment]
I'm still seeing ","

**Comment by brian-brazil** [comment]
There's still whitespace missing after commas.

**Comment by brian-brazil** [comment]
Great thank! There's one more pending change I want to get in before the next release.

**Comment by davidkarlsen** [comment]
@brian-brazil any ETA on that?

**Comment by brian-brazil** [comment]
I'm waiting on #173. Are you in a hurry for a release?

**Comment by davidkarlsen** [comment]
The missing IBM JDK support is a bit of a showstopper for us - but I guess I can wait a few days/ a week. Else I like the release early release often approach.

**Comment by davidkarlsen** [comment]
With #173 on board now - could you roll a release? It would be much appreciated.

**Comment by brian-brazil** [comment]
I'll do it in the next few days.

**Comment by davidkarlsen** [comment]
Awesome - thanks!
