### PR TITLE
fix NPE in PrometheusMvcEndpoint.value()

### LINKED ISSUE #252: PrometheusMvcEndpoint.java NPE for missing name parameter
Tested on simpleclient_spring_boot-0.0.23.jar.
Prometheus GET returns http error code 406. 
```
curl -v -H "Accept: text/plain; version=0.0.4; charset=utf-8" http://localhost:8956/prometheus
* timeout on name lookup is not supported
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8956 (#0)
> GET /prometheus HTTP/1.1
> Host: localhost:8956
> User-Agent: curl/7.53.1
> Accept: text/plain; version=0.0.4; charset=utf-8
>
< HTTP/1.1 406
< X-Application-Context: application:8956
< Content-Length: 0
< Date: Wed, 07 Jun 2017 09:00:12 GMT
```

But the same code works for `Accept */*`
```
curl -v http://localhost:8956/prometheus
* timeout on name lookup is not supported
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8956 (#0)
> GET /prometheus HTTP/1.1
> Host: localhost:8956
> User-Agent: curl/7.53.1
> Accept: */*
>
< HTTP/1.1 200
< X-Application-Context: application:8956
< Content-Type: application/vnd.spring-boot.actuator.v1+json;charset=UTF-8
< Content-Length: 11688
< Date: Wed, 07 Jun 2017 09:01:18 GMT
```

406 path goes directly to PrometheusMvcEndpoint.value() and fails on NPE inside CollectorRegistry.includedCollectorIterator(). 
200 path goes thru actuator directly to PrometheusEndpoint.invoke(), Content-Type in the response is different.

### PR DESCRIPTION
**Pull request by sunghyuk**
it resolves #252

### CODE REVIEW

**Comment by brian-brazil** [comment]
Could you add a unittest for this?

File: simpleclient_spring_boot/src/test/java/io/prometheus/client/spring/boot/PrometheusMvcEndpointTest.java [hunk 1]
```diff
@@ -0,0 +1,57 @@
...
+import org.springframework.http.*;
+import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
+import org.springframework.test.web.servlet.MockMvc;
+import org.springframework.web.client.RestTemplate;
+
+import static org.junit.Assert.*;
+import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
+import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
+
+/**
```
Comment (brian-brazil) [inline simpleclient_spring_boot/src/test/java/io/prometheus/client/spring/boot/PrometheusMvcEndpointTest.java]: Please remove this, git tracks history.

File: simpleclient_spring_boot/src/test/java/io/prometheus/client/spring/boot/PrometheusMvcEndpointTest.java [hunk 2]
```diff
@@ -0,0 +1,57 @@
...
+import org.apache.commons.lang3.StringUtils;
+import org.junit.Test;
+import org.junit.runner.RunWith;
+import org.mockito.Mock;
+import org.springframework.beans.factory.annotation.Autowired;
+import org.springframework.beans.factory.annotation.Value;
+import org.springframework.boot.test.SpringApplicationConfiguration;
+import org.springframework.boot.test.TestRestTemplate;
+import org.springframework.boot.test.WebIntegrationTest;
+import org.springframework.http.*;
```
Comment (brian-brazil) [inline simpleclient_spring_boot/src/test/java/io/prometheus/client/spring/boot/PrometheusMvcEndpointTest.java]: Explicit imports please

File: simpleclient_spring_boot/src/test/java/io/prometheus/client/spring/boot/PrometheusMvcEndpointTest.java [hunk 3]
```diff
@@ -0,0 +1,57 @@
...
+        HttpHeaders headers = new HttpHeaders();
+        headers.set("Accept", "text/plain; version=0.0.4; charset=utf-8");
+        HttpEntity entity = new HttpEntity(headers);
+
+        ResponseEntity metricsResponse = template.exchange(getBaseUrl() + "/prometheus?name[]=foo_bar", HttpMethod.GET, entity, String.class);
+        // then:
+        assertEquals(HttpStatus.OK, metricsResponse.getStatusCode());
+        assertTrue(StringUtils.deleteWhitespace(TextFormat.CONTENT_TYPE_004).equals(metricsResponse.getHeaders().getContentType().toString()));
+
+        // if name param is null, it should be initialized as an empty array.
```
Comment (brian-brazil) [inline simpleclient_spring_boot/src/test/java/io/prometheus/client/spring/boot/PrometheusMvcEndpointTest.java]: This would make sense as two separate functions I think, one testing with params and one without.

**Comment by sunghyuk** [comment]
thank you

File: simpleclient_spring_boot/src/test/java/io/prometheus/client/spring/boot/PrometheusMvcEndpointTest.java [hunk 4]
```diff
@@ -0,0 +1,62 @@
...
+import org.springframework.http.HttpMethod;
+import org.springframework.http.HttpStatus;
+import org.springframework.http.ResponseEntity;
+import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
+import org.springframework.web.client.RestTemplate;
+
+import static org.junit.Assert.assertEquals;
+import static org.junit.Assert.assertTrue;
+
+/**
```
Comment (brian-brazil) [inline simpleclient_spring_boot/src/test/java/io/prometheus/client/spring/boot/PrometheusMvcEndpointTest.java]: This is still here, please remove it.

File: simpleclient_spring_boot/src/test/java/io/prometheus/client/spring/boot/PrometheusMvcEndpointTest.java [hunk 5]
```diff
@@ -0,0 +1,62 @@
...
+public class PrometheusMvcEndpointTest {
+
+    @Value("${local.server.port}")
+    int localServerPort;
+
+    RestTemplate template = new TestRestTemplate();
+
+    @Test
+    public void testNameParamIsNull() throws Exception {
+        // if name param is null, it should be initialized as an empty array.
```
Comment (brian-brazil) [inline simpleclient_spring_boot/src/test/java/io/prometheus/client/spring/boot/PrometheusMvcEndpointTest.java]: I'd remove the comments here and below, they're not really adding anything.

**Comment by brian-brazil** [comment]
Thanks!

**Comment by sanjaychandak** [comment]
I am using 0.0.23 with Spring Boot 1.5.4.RELEASE but still I get the java.lang.NullPointerException: null
at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.includedCollectorIterator(CollectorRegistry.java:148)

Which version has this issue been fixed?

**Comment by brian-brazil** [comment]
@sanjaychandak Please don't spam bugs.

**Comment by sanjaychandak** [comment]
Sorry for that as I was trying to track the right thread to add my message.
